name: Debug Builds

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        java: [17]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: GradleW checksum check
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
          cache: "gradle"

      - name: Grant execute permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with: 
          name: legacy-vulkanmod
          path: build/libs/*.jar
